/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP TABLE IF EXISTS `Trasmissione`;
DROP TABLE IF EXISTS `Utente`;
DROP TABLE IF EXISTS `WeakEntity`;

CREATE TABLE `Trasmissione` (
  `Nome` varchar(64) NOT NULL DEFAULT '',
  `Utente` varchar(16) NOT NULL REFERENCES `Utente`.`CF` ON UPDATE CASCADE ON DELETE CASCADE,
  PRIMARY KEY (`Nome`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `Utente` (
  `Nome` varchar(32) DEFAULT NULL,
  `Cognome` varchar(32) DEFAULT NULL,
  `CF` varchar(16) NOT NULL,
  PRIMARY KEY (`CF`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `WeakEntity` (
  `a_val` int(11) NOT NULL,
  `utente` varchar(16) NOT NULL,
  PRIMARY KEY (`utente`),
  CONSTRAINT `WeakEntity_ibfk_1` FOREIGN KEY (`utente`) REFERENCES `Utente` (`CF`) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

LOCK TABLES `Utente` WRITE;
/*!40000 ALTER TABLE `Utente` DISABLE KEYS */;
INSERT INTO `Utente` VALUES
('Pippo','Improta','PPO'),
('Tiberio','Timperi','TTRI');
/*!40000 ALTER TABLE `Utente` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `Trasmissione` WRITE;
/*!40000 ALTER TABLE `Trasmissione` DISABLE KEYS */;
INSERT INTO `Trasmissione` VALUES
('Crack si gira', 'PPO');
/*!40000 ALTER TABLE `Trasmissione` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `WeakEntity` WRITE;
/*!40000 ALTER TABLE `WeakEntity` DISABLE KEYS */;
INSERT INTO `WeakEntity` VALUES (18,'TTRI');
/*!40000 ALTER TABLE `WeakEntity` ENABLE KEYS */;
UNLOCK TABLES;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;